### ISSUE TITLE
[Question] Middleware Positioning

### ISSUE THREAD

**Issue by ayushsharma82** [dbartholomae/middy-middleware-jwt-auth#141]
Hi,

Thanks for the lib, it's certainly very helpful.

I have a question about `HTTPErrorHandler` middleware which is used along with this library. Should `HTTPErrorHandler` be positioned above JWT Auth middleware or below it?

The author of `HTTPErrorHandler` suggests it to be the last one and the example provided with this middleware uses it on top.

**Comment by dbartholomae** [comment]
From my understanding of how middy handles error middleware, it should not make a difference, as the jwt-auth middleware does not implement an error handler and therefore does not compete for priority with the error middleware.

**Comment by ayushsharma82** [comment]
@dbartholomae  I see, Thanks for the clarification!
