### ISSUE TITLE
NPM install does not bring in jsonwebtoken v9.0.0 dependency

### ISSUE THREAD

**Issue by bradkelso32** [dbartholomae/middy-middleware-jwt-auth#283]
## Describe the bug
When doing a "npm i middy-middleware-jwt-auth@latest" command, the package-lock.json installs "jsonwebtoken": "^8.5.1" instead of "jsonwebtoken": "^9.0.0". The version of middy-middleware-jwt-auth being used is 5.1.1.

## To Reproduce
use npm to install middy-middleware-jwt-auth and check in the node_modules folder for the package and then open up its package.json file

## Expected behavior
jsonwebtoken v9.0.0 should be stated in the package.json

## Additional context
Also not sure if this is relevant but when I check the npmks.com website for this package (https://www.npmjs.com/package/middy-middleware-jwt-auth?activeTab=explore), the package.json that it has shows jsonwebtoken v8.5.1

Have tried to do a "npm cache clean --force" command.

**Comment by dbartholomae** [comment]
Thanks! I'll update the dependency.

**Comment by dbartholomae** [comment]
Thanks for bringing this up! Currently, dependency changes are not automatically released and need manual intervention. `middy-middleware-jwt-auth` is now available as [version 6.0.0](https://www.npmjs.com/package/middy-middleware-jwt-auth) with a dependency on jsonwebtoken 9.
