### ISSUE TITLE
IAuthorizedEvent is not a superset of APIGatewayEvent

### ISSUE THREAD

**Issue by parkan** [dbartholomae/middy-middleware-jwt-auth#86]
**Describe the bug**
I would expect the `IAuthorizedEvent` type to extend `APIGatewayEvent` as it replaces the event passed into the handler. However, this type only contains the headers and httpMethod members from APIGatewayEvent, not the [numerous other members](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/aws-lambda/trigger/api-gateway-proxy.d.ts#L65) (path, body, queryStringParameters, etc), which means the handler can no longer access the request in a useful way.

Is there a different invocation pattern that will retain access to those elements?

**To Reproduce**
I am using middy as follows (with netlify functions):

```
exports.handler = middy(async (
  event: APIGatewayEvent,
  context: Context
) => {
  switch (event.httpMethod) {
    case 'POST':
      return await handle(event, context);
    case 'OPTIONS':
      return { statusCode: 200 };
    case 'GET':
    case 'PUT':
    case 'DELETE':
      throw new Error("Not implemented");
  }
})
  .use(httpUrlEncodePathParser())
  .use(httpHeaderNormalizer())
  .use(httpErrorHandler())
  .use(JWTAuthMiddleware({
    algorithm: EncryptionAlgorithms.ES256,
    credentialsRequired: true,
    secretOrPublicKey: process.env.SECRET!
  }))
```

However, this does not typecheck, as the handler no longer has access to the members it needs.

**Expected behavior**
The original APIGatewayEvent is passed to the handler, enriched with an `auth` member.

**Additional context**
The way I'm invoking middy is slightly different from your example. However, I don't see how you'd be able to get useful info out of the event in either case.

**Comment by dbartholomae** [comment]
Thanks! From my understanding it is not possible to hand through the typing from the middleware to the handler in middy. That's the main reason that I built [lambda-middleware](https://github.com/dbartholomae/lambda-middleware).
For the handler itself you can do the following:

```ts
const helloWorld = async (event: IAuthorizedEvent<ITokenPayload> & ApiGatewayEvent) => {
  ...
}
```

**Comment by parkan** [comment]
@dbartholomae thanks for pointing me at lambda-middleware, looks like it's gonna solve a problem I didn't even know I had :) the way middy passes state through the middleware chain isn't very clean, this is much better
