### ISSUE TITLE
Example using Public Certificate

### ISSUE THREAD

**Issue by simonphughes** [dbartholomae/middy-middleware-jwt-auth#87]
I have an application integrated to Auth0 and using JWT tokens which i would like to use this code. I have set the algorithm to match Auth0 at RS512, and I am passing in the string starting with  -----BEGIN PUBLIC KEY. I have tried a few combinations of the string with \n replacing a carriage return, but I always get the error that the token is not valid.

Any chance of an example of how to use public keys correctly.
Thanks

**Comment by dbartholomae** [comment]
Hi! I don't have an example, but the middleware just passes the values to https://www.npmjs.com/package/jsonwebtoken, which is a library with more than 6 million downloads and therefore there might be some good examples how to use with public keys.
I remember having used this middleware with a public key before, but unfortunately don't have the code anymore.
